version: '3'
services:
  angular:
    build: ./
    ports:
      - '4000:4000'
    networks:
      - backend
  nginx:
    build: ./nginx
    depends_on:
      - angular
    networks:
      - backend
    ports:
      - 80:80
networks:
  backend:
    driver: bridge
